#spring全局配置
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
  application:
    name: wb-demo-redis
  redis:
    host: 127.0.0.1
    port: 16379
    password: Nariit@123
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  cache:
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis

server:
  port: 8085
  servlet:
    context-path: /wb-demo
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 100000000

