#spring全局配置
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
  application:
    name: wb-demo-redis
  redis:
    host: 127.0.0.1
    port: 16379
    password: Nariit@123
    database: 0

server:
  port: 8085
  servlet:
    context-path: /wb-demo-redis
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 100000000

