ok:
  http:
    connect-timeout: 30
    # 连接空闲时间最多为 300 秒
    keep-alive-duration: 300
    # 连接池中整体的空闲连接的最大数量
    max-idle-connections: 200
    read-timeout: 30
    write-timeout: 30


server:
  port: 8085
  servlet:
    context-path: /wb-demo