#spring全局配置
# xxl-job 服务端见开源项目
spring:
  application:
    name: wb-demo
server:
  port: 8086
  servlet:
    context-path: /wb-demo

logging:
  config: classpath:logback.xml
xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      address: ''
      app-name: xxl-job-executor-sample
      ip: 127.0.0.1
      log-path: /data/applogs/xxl-job/jobhandler
      log-retention-days: 30
      port: 9999
