#spring全局配置
spring:
  profiles:
    active: pro
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
  application:
    name: wb-demo
server:
  port: 8085
  servlet:
    context-path: /wb-demo
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 100000000

#mybatis-plus配置
mybatis-plus:
  global-config:
    enable-sql-runner: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml,classpath*:com/spring/demo/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true #是否开启

jasypt:
  encryptor:
    bean: myStringEncryptor